apiVersion: v2
name: Todo
description: Umbrella chart for Todo App (backend + frontend)
type: application
version: 0.0.4
appVersion: "0.0.4"

dependencies:
- name: backend
  version: 0.0.4
  repository: "file://backend"
- name: frontend
  version: 0.0.4
  repository: "file://frontend"
