{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/component: {{ include "frontend.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:{{ if .hosts }}
      {{- range .hosts }}
      - {{ . | quote }}
      {{ end }}{{ else }}
      - todo-frontend.todo.svc.cluster.local{{ end }}
      secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
    - host: {{ if .Values.ingress.host }}"{{ .Values.ingress.host }}"{{ else }}"{{ (include "frontend.fullname" .) | default "todo-frontend" }}.{{ .Release.Namespace }}.svc.cluster.local"{{ end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.serviceName | default "todo-frontend" }}
                port:
                  number: {{ .Values.ingress.port | default 80 }}
{{- end }}
