apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-nginx-vhost
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/component: {{ include "frontend.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

data:
  default.conf: |
    {{- $svcName := default (include "frontend.fullname" .) .Values.service.name }}
    {{- $svcNS := default .Release.Namespace .Values.service.namespace }}
    {{- $svcPort := int (default 8080 .Values.backend.port) }}
    {{- $svcFQDN := printf "%s.%s.svc.cluster.local:%d" $svcName $svcNS $svcPort }}
    upstream backend {
      server {{ $svcFQDN }};
    }

    server {
      listen 80;
      server_name _;

      root /usr/share/nginx/html;
      index index.html;

      location / {
        try_files $uri $uri/ /index.html;
      }

      location /todos {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
      }

      error_page 500 502 503 504 /50x.html;
      location = /50x.html {
        internal;
        root /usr/share/nginx/html;
      }
    }