apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-nginx-vhost
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/component: {{ include "frontend.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

data:
  default.conf: |
    {{- $AppName := default "backend" }}
    {{- $defaultPort := "8080" }}
    {{- $svcPort := int (default $defaultPort .Values.backend.port) }}

    {{- $ReleaseName := .Release.Name }}
    {{- $svcNS := default .Release.Namespace }}

    {{- $defaultHost := printf "%s-%s.%s.svc.cluster.local" $ReleaseName $AppName $svcNS }}
    {{- $svcFQDN := default $defaultHost .Values.backend.host }}
    upstream backend {
      server {{ $svcFQDN }}:{{ $svcPort }};
    }

    server {
      listen 80;
      server_name _;

      root /usr/share/nginx/html;
      index index.html;

      location / {
        try_files $uri $uri/ /index.html;
      }

      location /todos {
      {{ if eq $svcPort 443 }}
        proxy_pass https://backend;
        proxy_ssl_verify   off;
        proxy_ssl_server_name on;
      {{ else }}
        proxy_pass http://backend;
      {{end }}
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
      }

      error_page 500 502 503 504 /50x.html;
      location = /50x.html {
        internal;
        root /usr/share/nginx/html;
      }
    }