apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    alloy.io/scrape: "true"
    loki.io/logs: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.listenPort | default "8080" | quote }}
    prometheus.io/path: "/metrics"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name  | quote }}
      app.kubernetes.io/name: {{ .Chart.Name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/name: {{ .Chart.Name | quote }}
      annotations:
        alloy.io/scrape: "true"
        loki.io/logs: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.service.listenPort | default "8080" | quote }}
        prometheus.io/path: "/metrics"
    spec:
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-{{ .Chart.Name }}"
        {{- else }}
        - name: data
          emptyDir: {}
        {{- end }}
        - name: init-script
          configMap:
            name: "{{ .Release.Name }}-{{ .Chart.Name }}-init-script"
            defaultMode: 0755
      #securityContext:
      #  fsGroup: 200
      containers:
        - name: {{ .Chart.Name | quote }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.service.listenPort | default "8080" }}
              name: http
          env:
            - name: listenPort
              value: "{{ .Values.service.listenPort | default "8080" }}"
            - name: storage
              value: "{{ .Values.service.storage | default "/data/todoapp.db" }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            httpGet:
                path: /healthz
                port: {{ .Values.service.listenPort | default "8080" }}
            periodSeconds: 30
          livenessProbe:
            httpGet:
                path: /healthz
                port: {{ .Values.service.listenPort | default "8080" }}
            initialDelaySeconds: 60
            periodSeconds: 30
