apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-init-script"
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  init.sh: |
    #!/bin/sh
    {{- $AppName := default .Chart.Name  }}
    {{- $ReleaseName := default .Release.Name  }}
    {{- $svcNS := default .Release.Namespace }}
    {{- $svcPort := int (default 8000 .Values.service.port) }}
    {{- $svcFQDN := printf "%s-%s.%s.svc.cluster.local:%d" $ReleaseName $AppName $svcNS $svcPort }}
    until curl -sf http://{{ $svcFQDN }}/healthz; do
      echo "{\"level\":\"info\", \"message\":\"Waiting for {{ .Release.Name }} to be ready\"}"
      sleep 5
    done
    echo '{"level":"info", "message":"Created first todo"}'
    curl -s -X POST 'http://{{ $svcFQDN }}/todos' \
      -H 'accept: application/json' -H 'Content-Type: application/json' \
      -d '{"text":"First test todo" }'
    echo '{"level":"info", "message":"Init completed"}'
