apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-init-script
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/component: {{ include "backend.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  init.sh: |
    #!/bin/sh
    # Wait for todoapp to be ready
    {{- $svcName := default (include "backend.fullname" .) .Values.service.name }}
    {{- $svcNS := default .Release.Namespace .Values.service.namespace }}
    {{- $svcPort := int (default 8080 .Values.service.port) }}
    {{- $svcFQDN := printf "%s.%s.svc.cluster.local:%d" $svcName $svcNS $svcPort }}
    until curl -sf http://{{ $svcFQDN }}/healthz; do
      echo "{\"level\":\"info\", \"message\":\"Waiting for {{ .Release.Name }} to be ready\"}"
      sleep 5
    done
    echo '{"level":"info", "message":"Created first todo"}'
    curl -s -X POST 'http://{{ $svcFQDN }}/todos' \
      -H 'accept: application/json' -H 'Content-Type: application/json' \
      -d '{"text":"First test todo" }'
    echo '{"level":"info", "message":"Init completed"}'