apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-init-job"
  labels:
  {{- include "labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "hook-succeeded"
    "helm.sh/hook-weight": "5"
spec:
  template:
    spec:
      volumes:
        - name: init-script-volume
          configMap:
            name: "{{ .Release.Name }}-{{ .Chart.Name }}-init-script"
            defaultMode: 0755
      containers:
        - name: init-job-container
          image: curlimages/curl:8.1.2
          command: ["/scripts/init.sh"]
          volumeMounts:
            - name: init-script-volume
              mountPath: /scripts
      restartPolicy: OnFailure
  backoffLimit: 3