apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/chart-name: {{ .Chart.Name }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.port | default "8080" }}"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port | default "8080" }}
      targetPort: {{ .Values.service.listenPort | default "8080" }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
