service:
  enabled: true
  type: ClusterIP
  name: todo-backend
  port: 8080
  listenPort: 8080

persistence:
  enabled: true
  size: 256M
  storageClass: "" #"local-path"
  accessMode: ReadWriteOnce

ingress:
  enabled: true
  className: traefik
  #host: todo-backend.todo.svc.cluster.local
  serviceName: todo-backend
  tls:
  - secretName: todo-backend-tls
    hosts:
    - todo-backend.todo.svc.cluster.local
  annotations:
    kubernetes.io/ingress.className: traefik
    cert-manager.io/cluster-issuer: local-ca
    external-dns.alpha.kubernetes.io/hostname: todo-backend.todo.svc.cluster.local
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"

image:
  repository: foxmuldercp/go-todo-backend
  tag: 5efdb11 #latest
resources:
  requests:
    cpu: "100m"
    memory: "64Mb"
  limits:
    cpu: "200m"
    memory: "128Mb"
